### ISSUE TITLE
Shift+Enter throws error

### ISSUE THREAD

**Issue by thiccaxe** [withastro/cli-kit#32]
I added a `console.log(key)` in `action.js`

```
 astro   Launch sequence initiated.

╭─────╮  Houston:
│ ◠ ◡ ◠  Welcome to  astro  v4.9.2, thiccaxe!
╰─────╯
{
  sequence: '\r',
  name: 'return',

   dir   Where should we create your new project?
         ./satellite-sphere{
  sequence: '\r',
  name: 'return',
  ctrl: false,
  meta: false,

   dir   Where should we create your new project?
         ./satellite-sphere

  tmpl   How would you like to start your new project?
         ● Include sample files (recommended)
         ○ Use blog template 
         ○ Empty {
  sequence: '\x1BOM',
  name: 'undefined',
  ctrl: false,
  meta: false,
  shift: false,
  code: 'OM'
}
node:internal/readline/emitKeypressEvents:74
            throw err;
            ^

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at SelectPrompt._ (file:///home/thcx/Projects/ghangurde/node_modules/.pnpm/@astrojs+cli-kit@0.4.1/node_modules/@astrojs/cli-kit/dist/prompt/elements/select.js:59:26)
    at ReadStream.keypress (file:///home/thcx/Projects/ghangurde/node_modules/.pnpm/@astrojs+cli-kit@0.4.1/node_modules/@astrojs/cli-kit/dist/prompt/elements/prompt.js:29:32)
    at ReadStream.emit (node:events:519:28)
    at emitKeys (node:internal/readline/utils:371:14)
    at emitKeys.next (<anonymous>)
    at ReadStream.onData (node:internal/readline/emitKeypressEvents:64:36)
    at ReadStream.emit (node:events:531:35)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)

Node.js v20.13.1

```

**Comment by Sainan** [comment]
Just had the same thing pressing [Insert] on Windows

**Comment by thiccaxe** [comment]
Probably want something a bit more robust than the linked PR then. what do other projects do?
